version: '3.8'
services:
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - eventstore-data:/var/lib/eventstore
volumes:
  eventstore-data:
